In [2]:
pip list

Package               Version
--------------------- ----------
appdirs               1.4.4
argon2-cffi           21.3.0
argon2-cffi-bindings  21.2.0
asttokens             2.0.8
attrs                 22.1.0
backcall              0.2.0
bcrypt                3.2.0
beautifulsoup4        4.10.0
bleach                5.0.1
certifi               2021.10.8
cffi                  1.15.0
charset-normalizer    2.0.12
colorama              0.4.5
cryptography          36.0.2
cycler                0.11.0
dabl                  0.2.2
debugpy               1.6.3
decorator             5.1.1
defusedxml            0.7.1
email-scraper         0.4
entrypoints           0.4
executing             0.10.0
fastjsonschema        2.16.1
feedparser            6.0.8
fonttools             4.36.0
future                0.18.2
htmlmin               0.1.12
idna                  3.3
ImageHash             4.2.1
importlib-metadata    4.12.0
importlib-resources   5.9.0
ipykernel             6.15.1
ipython               8.4.0


NumPy aims provide an array object much 'better' than python. faster up to 50%.

In [3]:
import numpy as np

In [10]:
# create a 1-d array
li = [1,4,6,3,7]
arr1 = np.array(li)
arr1

array([1, 4, 6, 3, 7])

In [18]:
# create a 2-d array
arr2 = np.array([[1,2,4],[5,6,8]])
arr2[0][2]
len(arr2)

2

In [36]:
# create a 3-d array
arr3 = np.array([[[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]],[[1,2,3],[4,5,6]]])
#177
arr3[0][1][1][1]
# arr3[0,1,1]

C:\Users\core360\AppData\Local\Temp\ipykernel_10252\3058386644.py:2: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  arr3 = np.array([[[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]],[[1,2,3],[4,5,6]]])


5

Math Operation
-trigo
-logarithmic
-inverse
-exponential
-statistic

In [37]:
arr = np.array([1,3,5,2,6])

# cosine values
np.cos(arr)

array([ 0.54030231, -0.9899925 ,  0.28366219, -0.41614684,  0.96017029])

In [38]:
# logarithmic
np.log(arr)

array([0.        , 1.09861229, 1.60943791, 0.69314718, 1.79175947])

In [39]:
# mean
np.mean(arr)

3.4

In [40]:
# median
np.median(arr)

3.0

In [42]:
# stnadard deviation
np.std(arr)

1.8547236990991407

In [46]:
# addition of arrays
a1 = np.array([2,4,6,8,2])
a2 = np.array([3,6,1,5,2])

a1 + a2

array([ 5, 10,  7, 13,  4])

In [47]:
# subtraction of arrays
a1 = np.array([2,4,6,8,2])
a2 = np.array([3,6,1,5,2])

a1 - a2

array([-1, -2,  5,  3,  0])

In [48]:
# multiply of arrays
a1 = np.array([2,4,6,8,2])
a2 = np.array([3,6,1,5,2])

a1 * a2

array([ 6, 24,  6, 40,  4])

In [53]:
# create a 1d array that are all 1s
arr=np.ones(4)
arr

array([1., 1., 1., 1.])

In [66]:
# create a 2d array that are all 1s
arr=np.ones((2,2))
arr

array([[1., 1.],
       [1., 1.]])

In [71]:
# create a 3d array that are all 1s
arr=np.ones((2,2,2))
# arr=np.zeros((2,2,2))

arr

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

In [72]:
# dimension count

a = np.array([1,2,3])
b = np.array([[1., 1.],[1., 1.]])
c = np.array([[[1., 1.],[1., 1.]], [[1., 1.],[1., 1.]]])

a.ndim
b.ndim
c.ndim

3

In [78]:
# create an n-d array
arr = np.array([1,2,3,4],ndmin=6)
arr
arr.ndim

6

In [82]:
# slicing array
arr = np.array([1,2,3,4,5,6,7,8,9,10])
arr[0:5]
arr[3:]
arr[:6]

array([1, 2, 3, 4, 5, 6])

In [83]:
# slicing array from right (negative number)
arr = np.array([1,2,3,4,5,6,7,8,9,10])
arr[-3:-1]

array([8, 9])

In [85]:
# slicing 2d arrays
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
arr[1,0:3]

array([6, 7, 8])

In [87]:
# copy and view
# copy - owns array, changes made to the copy will not affect orig array
# view - does not own array, changes made to view will affect the orig array

arr = np.array([1,2,3,4,5])
arrcopy = arr.copy()
arrcopy[0] = 42

print(arr)
print(arrcopy)


[1 2 3 4 5]
[42  2  3  4  5]


In [90]:
# copy and view
# copy - owns array, changes made to the copy will not affect orig array
# view - does not own array, changes made to view will affect the orig array

arr = np.array([1,2,3,4,5])
arrview = arr.view()
arr[0] = 420

print(arr)
print(arrview)

[420   2   3   4   5]
[420   2   3   4   5]


In [92]:
# reshaping

# convert 1d array with 12 elements --> 2-d array with 3 elements
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
# 4 arrays with 3 elements each
newarr = arr.reshape(4,3)
print(arr)
print(newarr)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [93]:
# convert 1d array with 12 elements --> 3-d array 
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
# 2 arrays with 3 arrays with 2 elements each
newarr = arr.reshape(2,3,2)
print(arr)
print(newarr)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [94]:
# joining
a = np.array([1,2,3])
b = np.array([4,5,6])
arr = np.concatenate((a,b))
arr

array([1, 2, 3, 4, 5, 6])

In [106]:
# joining 2 2d array
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])

arr1 = np.concatenate((a,b))
arr2 = np.concatenate((a,b),axis=1)

print('arr1:' + str(arr1) + '\n')
print('arr2:' + str(arr2))

arr1:[[1 2]
 [3 4]
 [5 6]
 [7 8]]

arr2:[[1 2 5 6]
 [3 4 7 8]]


In [112]:
# Stacking
# vertical stack
a1 = np.array([1,2,3])
a2 = np.array([4,5,6])
a3 = np.array([7,8,9])

v_arr = np.vstack((a1,a2,a3))
h_arr = np.hstack((a1,a2,a3))

print(v_arr)
print(h_arr)


[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 2 3 4 5 6 7 8 9]


In [119]:
# splitting

# split array to 3 parts
a = np.array([1,2,3,4,5,6,7])
newarr = np.array_split(a,3)
newarr


[array([1, 2, 3]), array([4, 5]), array([6, 7])]

In [123]:
# split the 2-d array into 3 2-d array
a = np.array([[1,2],[3,4],[5,6],[7,8],[9,10],[11,12]])
newarr = np.array_split(a,3)
print(newarr)
print(newarr[0])

[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10],
       [11, 12]])]
[[1 2]
 [3 4]]


In [129]:
# searching

# find index of a value
arr = np.array([1,2,3,4,5,6,7,8,9])
# x = np.where(arr==4)
x = np.where(arr>=4)      # output index position
x


(array([3, 4, 5, 6, 7, 8], dtype=int64),)

In [142]:
arr = np.array(['ford','toyota','honda'])
x = np.where(arr=='ford')
x

(array([0], dtype=int64),)

In [144]:
# example finding even number
arr = np.array([1,2,3,4,5,6,7,8,9])
x = np.where(arr%2==0)
x

(array([1, 3, 5, 7], dtype=int64),)

In [146]:
# sorting
# arr = np.array([3,5,1,6,4])
arr = np.array(['red','blue','green','black'])
np.sort(arr)

array(['black', 'blue', 'green', 'red'], dtype='<U5')

In [154]:
# populating values (data distribution)

# generate random numbers 

# gen 100 numbers, 1-d array, values: 3,5,7,9 
# 3 = .1, 5 = .3, 7 = .6 , 9 = 0

from numpy import random, array
x = random.choice([3,5,7,9],p=[0.1,0.3,0.5,0.1],size=(100))

# 2d array 3 rows and 5 values
y = random.choice([3,5,7,9],p=[0.1,0.3,0.5,0.1],size=(3,5))

print(x)
print(y)

[7 7 7 9 5 3 7 3 7 7 9 5 9 3 5 5 3 7 5 3 5 9 9 5 5 5 9 7 5 5 5 5 7 7 5 7 9
 3 7 5 3 7 7 7 5 7 5 5 7 9 5 7 7 7 7 9 9 7 7 7 9 3 7 7 5 7 7 3 5 7 7 5 9 9
 7 7 3 7 7 7 7 7 5 7 7 7 5 7 7 7 7 7 7 5 5 7 9 7 7 9]
[[7 7 7 7 3]
 [7 9 5 7 5]
 [5 5 7 5 7]]
